FROM docker.io/library/tomcat:9.0.105-jdk11

MAINTAINER "HWANG HYESUNG<hwanghs7008@g.skku.edu>"

RUN rm -rf /usr/local/tomcat/webapps/

ADD target/guardians.war /usr/local/tomcat/webapps/ROOT.war
ADD mariadb-java-client-3.5.3.jar /usr/local/tomcat/lib/